name: Build and Deploy

on:
  push:
    branches:
      - sveltekit

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Node.JS
        uses: actions/setup-node@v1
        with:
          node-version: '16.13.1'

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6
          run_install: |
          - recursive: true
            args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Run eslint linter
        run: pnpm run lint

      - name: Build website
        run: pnpm run build

      # - name: Deploy 🚀
      #   uses: JamesIves/github-pages-deploy-action@4.1.0
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: gh-pages # The branch the action should deploy to.
      #     folder: dist # The folder the action should deploy.
